### ISSUE TITLE
can  you please do a video

### ISSUE THREAD

**Issue by justnothi** [MatthewCash/kahoot-bot#2]
if this is abanonded i stared it

**Comment by andreasgerner** [comment]
What exacty is your issue? I mean everything is pointed out in the readme

**Comment by justnothi** [comment]
ok

**Comment by justnothi** [comment]
im just new to this coding thing

**Comment by justnothi** [comment]
the cli

**Comment by justnothi** [comment]
where do i put the code

**Comment by andreasgerner** [comment]
oh gosh that's not what issues are for...

anyway, here's what you have to do:
1. Make sure you have git and node installed
2. Install ts-node globally (`npm i -g ts-node`)
3. Clone the repo (`git clone https://github.com/MatthewCash/kahoot-bot.git`)
4. Install the dependencies (`npm i`)
5. Follow the readme (`ts-node cli.ts CODE NAME COUNT`)

If you don't want to learn coding and just have some fun in Kahoot it's fine, otherwise you really should start learning the basics and what is happening in above steps

**Comment by justnothi** [comment]
ok

**Comment by justnothi** [comment]
npm i what?

**Comment by andreasgerner** [comment]
just `npm i`, that's the short version for `npm install`

**Comment by justnothi** [comment]
it says error

**Comment by justnothi** [comment]
This is related to npm not being able to find a file

**Comment by justnothi** [comment]
"npm i"

**Comment by justnothi** [comment]
` sudo npm i? `

**Comment by andreasgerner** [comment]
you need to be in the cloned directory, `npm i` installs all dependencies listed in the package.json file

you really should start learning the basics of node man

**Comment by justnothi** [comment]
ok
